name: 'Common Steps'
description: 'Steps to build and push Docker images'

inputs:
  context:
    description: 'Build context directory'
    required: true
  image_name:
    description: 'Name of the Docker image'
    required: true
  github_token:
    description: 'GitHub token for authentication'
    required: true

outputs:
  tags:
    description: 'Docker image tags'
    value: ${{ steps.set_tags.outputs.tags }}

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install cosign
      if: github.event_name != 'pull_request'
      uses: sigstore/cosign-installer@v3.6.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.0.0

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@v3.0.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ inputs.github_token }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ inputs.image_name }}

    - name: Set tags
      id: set_tags
      run: |
        TAGS="${{ steps.meta.outputs.tags }}"
        echo "tags=${TAGS}" >> $GITHUB_OUTPUT
        echo "Set tags: ${TAGS}"
      shell: bash

    - name: Debug output
      run: |
        echo "Image name: ${{ inputs.image_name }}"
        echo "Context: ${{ inputs.context }}"
        echo "Tags: ${{ steps.set_tags.outputs.tags }}"
      shell: bash