// <auto-generated />
using System;
using Api.Datastore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Models.Users.UserInfoModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TokenCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("TokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ac7639cd-f488-442f-ae6f-5f00e1004f9e"),
                            Email = "r.w.flinterman@hotmail.com",
                            LastLogin = new DateTime(2024, 11, 2, 22, 18, 22, 83, DateTimeKind.Utc).AddTicks(1300),
                            Password = "Vj9BECZRhJgcuh9+LU3vYQ==",
                            PhoneNumber = "",
                            Token = "deqdCsDhKsfYxBLgHLsdHJWhsdpvEUULb6Ry99HEHproXQMdbqP3kXepYRwyGG2Ie64x38CAbsuzjdxUdGAkD3klDbQrMeB5a7J0",
                            TokenCreated = new DateTime(2024, 11, 2, 22, 18, 22, 83, DateTimeKind.Utc).AddTicks(1301),
                            TokenExpiry = new DateTime(2024, 12, 2, 22, 18, 22, 83, DateTimeKind.Utc).AddTicks(1302),
                            Username = "Ruben"
                        },
                        new
                        {
                            Id = new Guid("99a90e06-fc35-4d1a-bcbf-ff208738447b"),
                            Email = "user@user.com",
                            LastLogin = new DateTime(2024, 11, 2, 22, 18, 22, 83, DateTimeKind.Utc).AddTicks(1591),
                            Password = "vh8z0h/sJbBQxloSzZRTrw==",
                            PhoneNumber = "",
                            Token = "user_token",
                            TokenCreated = new DateTime(2024, 11, 2, 22, 18, 22, 83, DateTimeKind.Utc).AddTicks(1592),
                            TokenExpiry = new DateTime(2024, 12, 2, 22, 18, 22, 83, DateTimeKind.Utc).AddTicks(1592),
                            Username = "User"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
