name: "Bug Report"

# Optional fields
assignees: []
labels: "bug,needs-triage"
title: "Bug: [Brief description of the issue]"

# Body with user input sections
body:
  - type: markdown
    attributes:
      value: |
        ## Summary
        **A clear and concise description of the bug.**

  - type: textarea
    attributes:
      label: "Steps to Reproduce"
      description: "Provide steps to reproduce the behavior."
      placeholder: "1. Step one\n2. Step two\n3. Step three"

  - type: textarea
    attributes:
      label: "Expected Behavior"
      description: "What did you expect to happen?"

  - type: textarea
    attributes:
      label: "Actual Behavior"
      description: "What actually happened?"

  - type: textarea
    attributes:
      label: "Screenshots"
      description: "Add screenshots if applicable to help explain your problem."
      placeholder: "Paste any relevant screenshots here."

  - type: textarea
    attributes:
      label: "Environment"
      description: "Provide your environment details such as OS, browser version, etc."
      placeholder: "Operating System: Windows 10\nBrowser: Chrome 92"

  - type: textarea
    attributes:
      label: "Logs or Error Messages"
      description: "Attach any relevant logs or error messages."
      placeholder: "Paste any relevant logs here."

  - type: textarea
    attributes:
      label: "Additional Context"
      description: "Add any other context about the problem, such as workarounds or intermittent behavior."
      placeholder: "Add any additional context here."
