### Authenticated POST request
POST https://api.rubenflinterman.com/api/v1/auth/register
Content-Type: application/json

{
  "Username": "admin@admin.com",
  "Password": "admin_token"
}

> {% client.global.set("token", response.body.accessToken) %}

### Get user details with Bearer token
GET https://api.rubenflinterman.com/api/v1/user/admin
Authorization: Bearer {{token}}