#!/usr/bin/env bash
set -euo pipefail

SECRETS_DIR=./secrets
GITIGNORE_FILE=./.gitignore

mkdir -p "$SECRETS_DIR"
umask 077

new_b64_secret() {
  openssl rand -base64 "$1"
}

# Basic plaintext values
printf '%s' "pi" > "$SECRETS_DIR/pg_user"
printf '%s' "app" > "$SECRETS_DIR/pg_name"
printf '%s' "localhost" > "$SECRETS_DIR/jwt_issuer"
printf '%s' "localhost" > "$SECRETS_DIR/jwt_audience"

# Strong secrets
pg_password=$(new_b64_secret 24)
jwt_secret=$(new_b64_secret 32)
encryption_key=$(new_b64_secret 32)
cert_password=$(new_b64_secret 16)

printf '%s' "$pg_password" > "$SECRETS_DIR/pg_password"
printf '%s' "$jwt_secret" > "$SECRETS_DIR/jwt_secret"
printf '%s' "$encryption_key" > "$SECRETS_DIR/encryption_key"
printf '%s' "$cert_password" > "$SECRETS_DIR/cert_password"

# Full Postgres connection string (used by ConnectionStrings__Postgres_FILE)
printf '%s' "Host=db;Port=5432;Database=app;Username=pi;Password=$pg_password" > "$SECRETS_DIR/pg_connection_string"

# Generate a self-signed PKCS#12 certificate at `./secrets/certificate.pfx` if openssl is available
if command -v openssl >/dev/null 2>&1; then
  tmp_key=$(mktemp)
  tmp_crt=$(mktemp)
  openssl req -x509 -nodes -newkey rsa:2048 -keyout "$tmp_key" -out "$tmp_crt" -days 365 -subj "/CN=localhost" >/dev/null 2>&1
  openssl pkcs12 -export -inkey "$tmp_key" -in "$tmp_crt" -passout pass:"$cert_password" -out "$SECRETS_DIR/certificate.pfx"
  rm -f "$tmp_key" "$tmp_crt"
else
  cat >&2 <<'WARN'
openssl not found; skipping certificate generation.
Place a `certificate.pfx` into `./secrets` and set `cert_password` accordingly.
WARN
fi

# Set permissions: dir 700, files 600
chmod 700 "$SECRETS_DIR"
chmod 600 "$SECRETS_DIR"/* || true

# Update .gitignore without overwriting and avoid duplicates
declare -a IGNORES=(
  " "
  " "
  "### Generated by 'secret_gen.sg'"
  "secret_gen.sh"
  "/secrets/"
  "/keys/"
  "/app/certificate.pfx"
  "*.pfx"
  ".env"
  "/bin/"
  "/obj/"
  "/out/"
  "### End of generated entries"
)

# Ensure gitignore exists
if [ ! -f "$GITIGNORE_FILE" ]; then
  touch "$GITIGNORE_FILE"
  chmod 600 "$GITIGNORE_FILE" || true
fi

# Append missing entries
for entry in "${IGNORES[@]}"; do
  # Use exact-line match to avoid duplicates
  if ! grep -Fxq -- "$entry" "$GITIGNORE_FILE"; then
    printf '%s\n' "$entry" >> "$GITIGNORE_FILE"
  fi
done

printf 'Secrets written to `./secrets` and `./.gitignore` updated (do not commit secrets).\n'